---
- include: register.yml
  when: inventory_hostname in groups['panko-api']

- include: config.yml
  when: inventory_hostname in groups['panko-api']

- include: bootstrap.yml
  when: inventory_hostname in groups['panko-api']

- include: start.yml
  when: inventory_hostname in groups['panko-api']
