---
- project:
    check:
      jobs:
        - kolla-ansible-centos-source
        - kolla-ansible-ubuntu-source
        - kolla-ansible-oraclelinux-source
        - kolla-ansible-ubuntu-source-ceph
        - kolla-ansible-centos-source-ceph
        - kolla-ansible-oraclelinux-source-ceph
        - kolla-ansible-bifrost-centos-source:
            files: ^ansible\/roles\/bifrost\/.*
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - openstack-tox-lower-constraints
    periodic:
      jobs:
        - kolla-ansible-bifrost-centos-source
